
//GET REQUEST

export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAILURE="GET_PRODUCT_FAILURE"

//POST REQUEST

export const POST_PRODUCT_REQUEST="POST_PRODUCT_REQUEST"
export const POST_PRODUCT_SUCCESS="POST_PRODUCT_SUCCESS"
export const POST_PRODUCT_FAILURE="POST_PRODUCT_FAILURE"

//DELETE REQUEST


export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
